export const SEARCH_PHOTOS_PENDING = 'SEARCH_PHOTOS_PENDING';
export const SEARCH_PHOTOS_SUCCESS = 'SEARCH_PHOTOS_SUCCESS';
export const LOAD_MORE_PHOTOS_PENDING = 'LOAD_MORE_PHOTOS_PENDING';
export const LOAD_MORE_PHOTOS_SUCCESS = 'LOAD_MORE_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_REJECT = 'FETCH_PHOTOS_REJECT';
